apiVersion: batch/v1
kind: CronJob
metadata:
  name: value
  namespace: perfect-charge
spec:
  schedule: "5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: value
              image: ghcr.io/rhjensen79/perfect-charge/value:latest
              imagePullPolicy: Always
              command:
                - /bin/sh
                - -c
                - date; echo Hello from the Kubernetes cluster
              env:
                - name: BARRY_METER_ID
                  valueFrom:
                    secretKeyRef: 
                      name: barry
                      key: barry_meter_id
                - name: BARRY_TOKEN
                  valueFrom:
                      secretKeyRef:
                        name: barry
                        key: barry_token
          imagePullSecrets:
            - name: regcred

          restartPolicy: OnFailure

