apiVersion: batch/v1
kind: CronJob
metadata:
  name: test
  namespace: perfect-charge
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: value
              image: ghcr.io/rhjensen79/perfect-charge/value:sha-ff0c2c5d66e24397e4443c218f79ec1e3c6a4c93
              imagePullPolicy: IfNotPresent
              command:
                - /bin/sh
                - -c
                - date; echo Hello from the Kubernetes cluster
          restartPolicy: OnFailure

