apiVersion: batch/v1
kind: CronJob
metadata:
  name: test
  namespace: perfect-charge
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: value
              image: ghcr.io/rhjensen79/perfect-charge/value:latest
              imagePullPolicy: Always
              command:
                - /bin/sh
                - -c
                - date; echo Hello from the Kubernetes cluster
          restartPolicy: OnFailure

