apiVersion: apps/v1
kind: Deployment
metadata:
  name: perfect-charge
  namespace: perfect-charge
spec:
  selector:
    matchLabels:
      app: perfect-charge
  template:
    metadata:
      labels:
        app: perfect-charge
    spec:
      volumes:
        - name: shared-data
          emptyDir: {}
      imagePullSecrets:
        - name: regcred
      containers:
        - name: value
          image: ghcr.io/rhjensen79/perfect-charge/value:sha-eaf0e66b2093127167171fd29c6457553704669a
          imagePullPolicy: Always
          resources:
            requests:
              memory: 256Mi
              cpu: 250m
          env:
            - name: BARRY_METER_ID
              valueFrom:
                secretKeyRef:
                  name: barry
                  key: barry_meter_id
            - name: BARRY_TOKEN
              valueFrom:
                secretKeyRef:
                  name: barry
                  key: barry_token
          livenessProbe:
            exec:
              command:
                - python
                - liveness_probe.py
            initialDelaySeconds: 60
            periodSeconds: 300
          volumeMounts:
            - name: shared-data
              mountPath: /usr/src/app/data
        - name: control
          image: ghcr.io/rhjensen79/perfect-charge/control:sha-464f8afe0789ceb9c5bc2c64f4c18f2051f5a56b
          imagePullPolicy: Always
          resources:
            requests:
              memory: 256Mi
              cpu: 250m
          env:
            - name: EASEE_USER
              valueFrom:
                secretKeyRef:
                  name: easee
                  key: easee_user
            - name: EASEE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: easee
                  key: easee_password
          volumeMounts:
            - name: shared-data
              mountPath: /usr/src/app/data
        - name: log
          image: ghcr.io/rhjensen79/perfect-charge/log:sha-f54216331dd3e6c14846f6b74ced506274d76657
          imagePullPolicy: Always
          resources:
            requests:
              memory: 256Mi
              cpu: 250m
          volumeMounts:
            - name: shared-data
              mountPath: /data

