apiVersion: apps/v1
kind: Deployment
metadata:
  name: perfect-charge
  namespace: perfect-charge
spec:
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: perfect-charge
  template:
    metadata:
      labels:
        app: perfect-charge
    spec:
      volumes:
        - name: shared-data
          persistentVolumeClaim:
            claimName: perfect-charge-pvc
      imagePullSecrets:
        - name: regcred
      containers:
        - name: value
          image: ghcr.io/rhjensen79/perfect-charge/value:sha-37c4608b6abc9a1b8c550a598aefa2ecb884f9d1
          imagePullPolicy: Always
          resources:
            requests:
              memory: 256Mi
              cpu: 0.1m
          env:
            - name: BARRY_METER_ID
              valueFrom:
                secretKeyRef:
                  name: barry
                  key: barry_meter_id
            - name: BARRY_TOKEN
              valueFrom:
                secretKeyRef:
                  name: barry
                  key: barry_token
          livenessProbe:
            exec:
              command:
                - python
                - liveness_probe.py
            initialDelaySeconds: 60
            periodSeconds: 300
          volumeMounts:
            - name: shared-data
              mountPath: /usr/src/app/data
        - name: control
          image: ghcr.io/rhjensen79/perfect-charge/control:sha-37c4608b6abc9a1b8c550a598aefa2ecb884f9d1
          imagePullPolicy: Always
          resources:
            requests:
              memory: 256Mi
              cpu: 0.1m
          env:
            - name: EASEE_USER
              valueFrom:
                secretKeyRef:
                  name: easee
                  key: easee_user
            - name: EASEE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: easee
                  key: easee_password
          livenessProbe:
            exec:
              command:
                - python
                - liveness_probe.py
            initialDelaySeconds: 60
            periodSeconds: 300
          volumeMounts:
            - name: shared-data
              mountPath: /usr/src/app/data
        - name: log
          image: ghcr.io/rhjensen79/perfect-charge/log:sha-37c4608b6abc9a1b8c550a598aefa2ecb884f9d1
          imagePullPolicy: Always
          resources:
            requests:
              memory: 256Mi
              cpu: 0.1m
          volumeMounts:
            - name: shared-data
              mountPath: /data
        - name: monitoring
          image: ghcr.io/rhjensen79/perfect-charge/monitoring:sha-37c4608b6abc9a1b8c550a598aefa2ecb884f9d1
          imagePullPolicy: Always
          resources:
            requests:
              memory: 256Mi
              cpu: 0.1m
          volumeMounts:
            - name: shared-data
              mountPath: /usr/src/app/data

