apiVersion: apps/v1
kind: Deployment
metadata:
  name: perfect-charge
  namespace: perfect-charge
spec:
  selector:
    matchLabels:
      app: perfect-charge
  template:
    metadata:
      labels:
        app: perfect-charge
    spec:
      volumes:
        - name: shared-data
          persistentVolumeClaim:
            claimName: perfect-charge-pvc
      imagePullSecrets:
        - name: regcred
      containers:
        - name: value
          image: ghcr.io/rhjensen79/perfect-charge/value:sha-eaf0e66b2093127167171fd29c6457553704669a
          imagePullPolicy: Always
          resources:
            requests:
              memory: 256Mi
              cpu: 0.1m
          env:
            - name: BARRY_METER_ID
              valueFrom:
                secretKeyRef:
                  name: barry
                  key: barry_meter_id
            - name: BARRY_TOKEN
              valueFrom:
                secretKeyRef:
                  name: barry
                  key: barry_token
          livenessProbe:
            exec:
              command:
                - python
                - liveness_probe.py
            initialDelaySeconds: 60
            periodSeconds: 300
          volumeMounts:
            - name: shared-data
              mountPath: /usr/src/app/data
        - name: control
          image: ghcr.io/rhjensen79/perfect-charge/control:sha-3cddc136f735a915fb4cf19f29431e9a39ea4c8d
          imagePullPolicy: Always
          resources:
            requests:
              memory: 256Mi
              cpu: 0.1m
          env:
            - name: EASEE_USER
              valueFrom:
                secretKeyRef:
                  name: easee
                  key: easee_user
            - name: EASEE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: easee
                  key: easee_password
          volumeMounts:
            - name: shared-data
              mountPath: /usr/src/app/data
        - name: log
          image: ghcr.io/rhjensen79/perfect-charge/log:sha-f54216331dd3e6c14846f6b74ced506274d76657
          imagePullPolicy: Always
          resources:
            requests:
              memory: 256Mi
              cpu: 0.1m
          volumeMounts:
            - name: shared-data
              mountPath: /data
        - name: monitoring
          image: ghcr.io/rhjensen79/perfect-charge/monitoring:sha-afc8ad412b558b85dfba71beea64550950313c16
          imagePullPolicy: Always
          resources:
            requests:
              memory: 256Mi
              cpu: 0.1m
          volumeMounts:
            - name: shared-data
              mountPath: /usr/src/app/data
---
apiVersion: v1
kind: Service
metadata:
  name: perfect-charge-monitoring-service
  namespace: perfect-charge
spec:
  selector:
    app: monitoring
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: monitoring-perfect-charge
  namespace: perfect-charge
spec:
  secretName: tls-cert-pc-robert-jensen
  privateKey:
    rotationPolicy: Always
  dnsNames:
    - pc.robert-jensen.dk
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
    group: cert-manager.io

