apiVersion: apps/v1
kind: Deployment
metadata:
  name: perfect-charge
  namespace: perfect-charge
spec:
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: perfect-charge
  template:
    metadata:
      labels:
        app: perfect-charge
    spec:
      volumes:
        - name: shared-data
          persistentVolumeClaim:
            claimName: perfect-charge-pvc
      imagePullSecrets:
        - name: regcred
      containers:
        - name: value
          image: ghcr.io/rhjensen79/perfect-charge/value:sha-e0feef91708517fe58c7c4ba17e6463f6ddf9a97
          imagePullPolicy: Always
          resources:
            requests:
              memory: 256Mi
              cpu: 0.1m
          env:
            - name: BARRY_METER_ID
              valueFrom:
                secretKeyRef:
                  name: barry
                  key: barry_meter_id
            - name: BARRY_TOKEN
              valueFrom:
                secretKeyRef:
                  name: barry
                  key: barry_token
          livenessProbe:
            exec:
              command:
                - python
                - liveness_probe.py
            initialDelaySeconds: 60
            periodSeconds: 300
          volumeMounts:
            - name: shared-data
              mountPath: /usr/src/app/data
        - name: control
          image: ghcr.io/rhjensen79/perfect-charge/control:sha-4551e821b72df2befde77634f8aef38b16f861e5
          imagePullPolicy: Always
          resources:
            requests:
              memory: 256Mi
              cpu: 0.1m
          env:
            - name: EASEE_USER
              valueFrom:
                secretKeyRef:
                  name: easee
                  key: easee_user
            - name: EASEE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: easee
                  key: easee_password
          livenessProbe:
            exec:
              command:
                - python
                - liveness_probe.py
            initialDelaySeconds: 60
            periodSeconds: 300
          volumeMounts:
            - name: shared-data
              mountPath: /usr/src/app/data
        - name: log
          image: ghcr.io/rhjensen79/perfect-charge/log:sha-948b05b529f3120242adfbb5f35129c41e8e476d
          imagePullPolicy: Always
          resources:
            requests:
              memory: 256Mi
              cpu: 0.1m
          volumeMounts:
            - name: shared-data
              mountPath: /data
        - name: monitoring
          image: ghcr.io/rhjensen79/perfect-charge/monitoring:sha-aac671d28ed13e1d9fd61fab01c9e5d2718218b8
          imagePullPolicy: Always
          resources:
            requests:
              memory: 256Mi
              cpu: 0.1m
          volumeMounts:
            - name: shared-data
              mountPath: /usr/src/app/data
