name: Deploy only

on:
  push:
    branches: ['master']
    paths:
    - 'k8s/**'
  workflow_dispatch:

jobs:
  deploy-app-to-k8s:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Tailscale
      uses: tailscale/github-action@v1
      with:
        authkey: ${{ secrets.TAILSCALE_AUTHKEY }}
    - name: Set Kubernetes Context
      uses: azure/k8s-set-context@v2
      with:
        method: kubeconfig
        kubeconfig: ${{ secrets.KUBE_CONFIG }}
        context: microk8s
    - name: Deploy to Cluster
      run: |
        kubectl apply -f k8s/perfect-charge.yaml
